// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "CS1591:Missing XML comment for publicly visible type of member", Justification = "<Pending>", Scope = "")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "")]
[assembly: SuppressMessage("Usage", "RCS1155:Use StringComparison when comparing strings.", Justification = "<Pending>", Scope = "")]
[assembly: SuppressMessage("Minor Code Smell", "S1199:Nested code blocks should not be used", Justification = "<Pending>", Scope = "")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "")]
[assembly: SuppressMessage("Usage", "RCS1155:Use StringComparison when comparing strings.", Justification = "<Pending>", Scope = "")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "For clarify we like to use the using with brackets ", Scope = "")]
[assembly: SuppressMessage("Critical Vulnerability", "S4830:Server certificates should be verified during SSL/TLS connections", Justification = "These are for monitoring purposes where oranara agent overcomes technical issues related to SSL in order to fetch the data.", Scope = "")]
[assembly: SuppressMessage("Design", "RCS1102:Make class static.", Justification = "Not Important", Scope = "")]
[assembly: SuppressMessage("Major Code Smell", "S2971:\"IEnumerable\" LINQs should be simplified", Justification = "<Pending>", Scope = "")]
[assembly: SuppressMessage("Major Code Smell", "S2971:\"IEnumerable\" LINQs should be simplified", Justification = "<Pending>", Scope = "")]
[assembly: SuppressMessage("Using clear-text protocols is security-sensitive", "S5332", Justification = "This is part of the platform to do calls to secure and non secure targets", Scope = "")]
[assembly: SuppressMessage("Configuring loggers is security-sensitive", "S4792", Justification = "This is to configure seilog to be used the configuration file (appsettings)", Scope = "")]
[assembly: SuppressMessage("Searching OS commands in PATH is security-sensitive", "S4036", Justification = "the path should be relative since we it can vary from millions of users machines.", Scope = "")]
[assembly: SuppressMessage("Expanding archive files without controlling resource consumption is security-sensitive", "S5042", Justification = "The extracted files here are all fixed in size by dynamic by 1k key file", Scope = "")]
[assembly: SuppressMessage("\"operator==\" should not be overloaded on reference type", "S3875", Justification = "This is part of the architecture where we have context entities and detached entities and equality should prevale regardless of the source the instances came from.", Scope = "")]
[assembly: SuppressMessage("\"is\" should not be used with \"this\"", "S3060", Justification = "The warning is true except for the fact we are not using any child class specific code, its only to return a boolean value", Scope = "")]
[assembly: SuppressMessage("Instance members should not write to \"static\" fields", "S3060", Justification = "The warning is true except for the fact we are not using any child class specific code, its only to return a boolean value", Scope = "")]
[assembly: SuppressMessage("Tables should have headers", "S5256", Justification = "These tables are intended to not have a header therefore its not an issues.", Scope = "")]
[assembly: SuppressMessage("\"<table>\" tags should have a description", "TableWithoutCaptionCheck", Justification = "These tables are intended to not have a header therefore its not an issues.", Scope = "")]
[assembly: SuppressMessage("Cognitive Complexity of methods should not be too high", "S3776", Justification = "The complexities in the methods are non-avoidable due to the nature of logic required, plus clarity is assured", Scope = "")]
[assembly: SuppressMessage("Methods should not have too many parameters", "S107", Justification = "Its not important at all.", Scope = "")]
[assembly: SuppressMessage("Attributes deprecated in HTML5 should not be used", "S1827", Justification = "All these deprecated rely in html templates that will be replaced by their counter github templates", Scope = "")]
[assembly: SuppressMessage("Collapsible \"if\" statements should be merged", "S1066", Justification = "These if statements are split for readability purposes", Scope = "")]
[assembly: SuppressMessage("Methods should not have identical implementations", "S4144", Justification = "Few in the solution and these duplicates are for consistency purposes", Scope = "")]
[assembly: SuppressMessage("Reflection should not be used to increase accessibility of classes, methods, or fields", "S3011", Justification = "Not important as this is for the the log attribute only internal use.", Scope = "")]
[assembly: SuppressMessage("Aspect should contain effect", "AI_A000", Justification = "Not clear at all and AspectInjector doesnt provides mixins of effects", Scope = "")]
[assembly: SuppressMessage("Unused method parameters should be removed", "S1172", Justification = "Extra parameters are for couple of methods and left for extensibility reasons and future use", Scope = "")]
[assembly: SuppressMessage("Ternary operators should not be nested", "S3358", Justification = "In these cases left all are much clear and simpler to read and understand than spliting to if statements", Scope = "")]
[assembly: SuppressMessage("Classes implementing \"IEquatable<T>\" should be sealed", "S4035", Justification = "Not Important at all", Scope = "")]
[assembly: SuppressMessage("Inheritance list should not be redundant", "S1939", Justification = "Inheritence list is redundant for clarity purposes", Scope = "")]
[assembly: SuppressMessage("Types should be named in PascalCase", "S101", Justification = "All classes are compliant, but some classes has an abbreviate which is ok to partially violate it", Scope = "")]
[assembly: SuppressMessage("Hard-coded credentials are security-sensitive", "S2068", Justification = "not sensetive", Scope = "")]
[assembly: SuppressMessage("Amazon Web Services credentials should not be disclosed", "S6290", Justification = "not sensetive", Scope = "")]
[assembly: SuppressMessage("Google Cloud service accounts keys should not be disclosed", "S6335", Justification = "not sensetive", Scope = "")]
[assembly: SuppressMessage("Configuring loggers is security-sensitive", "S4792", Justification = "not sensetive", Scope = "")]
[assembly: SuppressMessage("Cognitive Complexity of methods should not be too high", "S3776", Justification = "not sensetive", Scope = "")]
[assembly: SuppressMessage("\"Explicit\" conversions of \"foreach\" loops should not be used", "S3217", Justification = "not sensetive", Scope = "")]
[assembly: SuppressMessage("Recursively copying context directories is security-sensitive", "docker:S6470", Justification = "not sensetive", Scope = "")]
[assembly: SuppressMessage("Method overrides should not change parameter defaults", "S1006", Justification = "not sensetive", Scope = "")]
[assembly: SuppressMessage("\"Find\" method should be used instead of the \"FirstOrDefault\" extension", "S6602", Justification = "not important at all", Scope = "")]
[assembly: SuppressMessage("Loops should be simplified with \"LINQ\" expressions", "S3267", Justification = "not important at all", Scope = "")]
[assembly: SuppressMessage("Classes should not be empty", "S2094", Justification = "not important at all", Scope = "")]
[assembly: SuppressMessage("Strings should not be concatenated using '+' in a loop", "S1643", Justification = "not important at all", Scope = "")]
[assembly: SuppressMessage("Mark members as static", "CA1822", Justification = "not important at all", Scope = "")]
[assembly: SuppressMessage("Track uses of \"TODO\" tags", "S1135", Justification = "not important at all", Scope = "")]
[assembly: SuppressMessage("Having a permissive Cross-Origin Resource Sharing policy is security-sensitive", "S5122", Justification = "Already handled as a configuration", Scope = "")]
[assembly: SuppressMessage("Attributes deprecated in HTML5 should not be used", "S1827", Justification = "Collections are small", Scope = "")]
[assembly: SuppressMessage("HTML \"<table>\" should not be used for layout purposes", "S5257", Justification = "Collections are small", Scope = "")]
[assembly: SuppressMessage("Aspect 'RecaptchaAttribute' does not have any effect", "AI_A000", Justification = "Not true", Scope = "")]
[assembly: SuppressMessage("Use the 'StringComparison' method overloads to perform case-insensitive string comparisons", "CA1862", Justification = "Not Important", Scope = "")]
